export const leftLinks = [
  { link1: "Questions", to: "/" },
  { link1: "Investor Relations", to: "/" },
  { link1: "Privacy", to: "/" },
  { link1: "Speed Test", to: "/" },
];

export const middleLinks = [
  { link2: "Help Center", to: "/" },
  { link2: "Jobs", to: "/" },
  { link2: "Cookies Preference", to: "/" },
  { link2: "Legal Notices", to: "/" },
];

export const assistLinks = [
  { link3: "Account", to: "/" },
  { link3: "Ways to Watch", to: "/" },
  { link3: "Cooperation Information", to: "/" },
  { link3: "Only on Netflix", to: "/" },
];

export const rightLinks = [
  { link4: "Media Centre", to: "/" },
  { link4: "Terms of Use", to: "/" },
  { link4: "Contact Us", to: "/" },
];

export const tvImages = [
  "/assets/landing-page.png",
  "/assets/cards/card1.jpg",
  "/assets/cards/card2.jpg",
  "/assets/cards/card3.jpg",
  "/assets/cards/card4.jpg",
  "/assets/cards/card5.jpg",
];

export const watchedImages = [
  "/assets/image8.png",
  "/assets/cards/card7.jpg",
  "/assets/cards/card8.jpg",
  "/assets/cards/card9.jpg",
  "/assets/cards/card10.jpg",
];

export const profileIcons = [
  { name: "Shekinah", src: "/assets/image12.png", edit: "/assets/image18.png" },
  { name: "Prince", src: "/assets/image11.png", edit: "/assets/image18.png" },
  { name: "Dave", src: "/assets/image13.png", edit: "/assets/image18.png" },
  { name: "Gideon", src: "/assets/image14.png", edit: "/assets/image18.png" },
  { name: "Ben", src: "/assets/image15.png", edit: "/assets/image18.png" },
  { name: "Junior", src: "/assets/image12.png", edit: "/assets/image18.png" },
];

export const headerLinks = [
  { name: "Home", to: "/" },
  { name: "TV Shows", to: "/tv-shows" },
  { name: "Movies", to: "/movies" },
  { name: "New & Popular", to: "/new-popular" },
  { name: "My List", to: "/my-list" },
  { name: "Browse by Languages", to: "/browse-by-languages" },
];

export const southIndian = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];

export const trendingNow = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const uSTVShow = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const adventureMovie = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const internationalTVShows = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const top10IndianMovies = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const madeInIndia = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const southCinemas = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const internationalMovies = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const newReleases = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const popularNetflix = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const tvComedies = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const bingeworthyTV = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const englishMovies = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
