export const leftLinks = [
  { link1: "Questions", to: "/" },
  { link1: "Investor Relations", to: "/" },
  { link1: "Privacy", to: "/" },
  { link1: "Speed Test", to: "/" },
];

export const middleLinks = [
  { link2: "Help Center", to: "/" },
  { link2: "Jobs", to: "/" },
  { link2: "Cookies Preference", to: "/" },
  { link2: "Legal Notices", to: "/" },
];

export const assistLinks = [
  { link3: "Account", to: "/" },
  { link3: "Ways to Watch", to: "/" },
  { link3: "Cooperation Information", to: "/" },
  { link3: "Only on Netflix", to: "/" },
];

export const rightLinks = [
  { link4: "Media Centre", to: "/" },
  { link4: "Terms of Use", to: "/" },
  { link4: "Contact Us", to: "/" },
];
export const SOCIAL_LINKS = {
  instagram: "https://www.instagram.com/shekinahwebdev",
  whatsapp: "https://chat.whatsapp.com/HvS0OfwO9qGEpfqHeUXz1T?mode=wwc",
} as const;

export const tvImages = [
  "/assets/landing-page.png",
  "/assets/cards/card1.jpg",
  "/assets/cards/card2.jpg",
  "/assets/cards/card3.jpg",
  "/assets/cards/card4.jpg",
  "/assets/cards/card5.jpg",
];

export const watchedImages = [
  "/assets/image8.png",
  "/assets/cards/card7.jpg",
  "/assets/cards/card8.jpg",
  "/assets/cards/card9.jpg",
  "/assets/cards/card10.jpg",
];

export const profileIcons = [
  { name: "Shekinah", src: "/assets/image12.png", edit: "/assets/image18.png" },
  { name: "Prince", src: "/assets/image11.png", edit: "/assets/image18.png" },
  { name: "Dave", src: "/assets/image13.png", edit: "/assets/image18.png" },
  { name: "Gideon", src: "/assets/image14.png", edit: "/assets/image18.png" },
  { name: "Ben", src: "/assets/image15.png", edit: "/assets/image18.png" },
  { name: "Junior", src: "/assets/image12.png", edit: "/assets/image18.png" },
];

export const headerLinks = [
  { name: "Home", to: "/" },
  { name: "TV Shows", to: "/tv-shows" },
  { name: "Movies", to: "/movies" },
  { name: "New & Popular", to: "/new-popular" },
  { name: "My List", to: "/my-list" },
  { name: "Browse by Languages", to: "/browse-by-languages" },
];

export const southIndian = [
  "/assets/cards/card1.jpg",
  "/assets/cards/card2.jpg",
  "/assets/cards/card3.jpg",
  "/assets/cards/card4.jpg",
  "/assets/cards/card5.jpg",
  "/assets/cards/card6.jpg",
  "/assets/cards/card7.jpg",
  "/assets/cards/card8.jpg",
  "/assets/cards/card9.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card11.jpg",
  "/assets/cards/card12.jpg",
  "/assets/cards/card13.jpg",
  "/assets/cards/card14.jpg",
  "/assets/cards/card15.png",
];

export const trendingNow = [
  "/assets/cards/card16.png",
  "/assets/cards/card17.png",
  "/assets/cards/card18.png",
  "/assets/cards/card19.png",
  "/assets/cards/card20.png",
  "/assets/cards/card21.png",
  "/assets/cards/card22.png",
  "/assets/cards/card23.png",
  "/assets/cards/card24.png",
  "/assets/cards/card25.png",
  "/assets/cards/card26.png",
  "/assets/cards/card27.png",
  "/assets/cards/card1.jpg",
  "/assets/cards/card2.jpg",
  "/assets/cards/card3.jpg",
  "/assets/cards/card4.jpg",
];
export const uSTVShow = [
  "/assets/cards/card6.jpg",
  "/assets/cards/card31.jpg",
  "/assets/cards/card32.jpg",
  "/assets/cards/card41.jpg",
  "/assets/cards/card29.jpg",
  "/assets/cards/card30.jpg",
  "/assets/cards/card33.jpg",
  "/assets/cards/card34.jpg",
  "/assets/cards/card35.jpg",
  "/assets/cards/card36.jpg",
  "/assets/cards/card40.jpg",
  "/assets/cards/card42.jpg",
  "/assets/cards/card43.jpg",
  "/assets/cards/card7.jpg",
  "/assets/cards/card9.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card5.jpg",
];
export const adventureMovie = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const internationalTVShows = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const top10IndianMovies = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const madeInIndia = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const southCinemas = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const internationalMovies = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const newReleases = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const popularNetflix = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const tvComedies = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const bingeworthyTV = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];
export const englishMovies = [
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
  "/assets/cards/card10.jpg",
];

export const trailers = [
  {
    name: "RRR",
    src: "/assets/Bheem For Ramaraju - Ramaraju Intro - RRR(Telugu) _ NTR, Ram Charan, Ajay Devgn _ SS Rajamouli (1) 1.png",
    description:
      "RRR is a fictional story about two Indian revolutionaries who fought against British colonialists in the 1920s. The film is set in the 1920s and spoken in the Telugu language.",
    videoUrl: "https://www.youtube.com/watch?v=GY4BgdUSpbE",
  },
  {
    name: "Jawan",
    src: "/assets/logo/jawan.png",
    description:
      "Avatar is an American media franchise created by James Cameron, which consists of a planned series of epic science fiction films produced by Lightstorm Entertainment ",
    videoUrl: "https://youtu.be/5PSNL1qE6VY?si=B5Pg2kP_8j3u-lOm",
  },
  {
    name: "Jurassic World Rebirth",
    src: "/assets/logo/jurassic.png",
    description:
      "A theme park showcasing genetically-engineered dinosaurs turns into a nightmare for its tourists when one of the dinosaurs escapes its enclosure. An ex-military animal expert steps up to save the day.",
    videoUrl: "https://youtu.be/RFinNxS5KN4?si=aJK1tozY0ZuLqIeM",
  },
  {
    name: "Meg 2: The Trench",
    src: "/assets/logo/mega.png",
    description:
      "Jonas Taylor leads a research team on an exploratory dive into the deepest depths of the ocean. Their voyage spirals into chaos when a malevolent mining operation threatens their mission",
    videoUrl: "https://youtu.be/dG91B3hHyY4?si=KOTFppeZeuKsKjA9",
  },
  {
    name: "Avatar",
    src: "/assets/logo/avatar.png",
    description:
      "Avatar is an American media franchise created by James Cameron, which consists of a planned series of epic science fiction films produced by Lightstorm Entertainment",
    videoUrl: "https://youtu.be/5PSNL1qE6VY?si=B5Pg2kP_8j3u-lOm",
  },
  {
    name: "Virupaksha",
    src: "/assets/logo/Virupaksha.png",
    description:
      "Virupaksha is a 2023 Indian Telugu-language horror thriller film directed by Karthik Varma Dandu who co-wrote the film with Sukumar.",
    videoUrl: "https://youtu.be/BC9s_Zof_Xk?si=LmMoYKjvG9U6ylpU",
  },
];

export const movieLogos: Record<string, string> = {
  RRR: "/assets/Bheem For Ramaraju - Ramaraju Intro - RRR(Telugu) _ NTR, Ram Charan, Ajay Devgn _ SS Rajamouli (1) 1.png",
  Avatar: "/assets/logo/avatar.png",
  Jawan: "/assets/logo/jawan.png",
  "Jurassic World Rebirth": "/assets/logo/jurassic.png",
  "Meg 2: The Trench": "/assets/logo/mega.png",
  Virupaksha: "/assets/logo/Virupaksha.png",
};
